services:
  traefik-public:
    command:
      - "--log.level=INFO"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.directory=/certs/traefik"
      - "--providers.file.watch=false"
      - "--entrypoints.websecure.address=:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "traefik_public_acme:/acme"
      - "./certs:/certs:ro"
    environment:
      - CF_DNS_API_TOKEN=
  traefik-lab:
    command:
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.traefik.address=:8888"
      - "--api=true"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--metrics.prometheus=true"
      - "--providers.consulcatalog=true"
      - "--providers.consulcatalog.endpoint.address=127.0.0.1:8500"
      - "--providers.consulcatalog.exposedbydefault=false"
      - "--providers.consulcatalog.prefix=traefik"
      - "--providers.file.directory=/certs/traefik"
      - "--providers.file.watch=false"
    volumes:
      - "traefik_lab_acme:/acme"
      - "./certs:/certs:ro"
    environment:
      - CF_DNS_API_TOKEN=